spring:
  profiles:
    active: ${environment}
    
datasource:
  db:
    driver-class-name:  com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/spring_app?useUnicode=true&characterEncoding=utf8
    name: 
    username: root
    password: <password>
    
hibernate:
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.use_query_cache:  false
    hibernate.generate_statistics:  true
    hibernate.cache.region.factory_class: com.spa.config.hazelcast.HazelcastCacheRegionFactory
    hibernate.cache.use_minimal_puts: true
    hibernate.cache.hazelcast.use_lite_member:  true
    
jpa:
    persistence-unit-name:  spring-app
    database-platform:  org.hibernate.dialect.MySQLInnoDBDialect
    database: MYSQL
    hibernate.show_sql: true
    hibernate.generated_ddl:  true
    hibernate.hbm2ddl.auto: update
    hibernate.dialect:  org.hibernate.dialect.MySQL5Dialect
 
